// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9Y6oG9Cwvwaz4v8_uek-wS5i-0A95H0',
    appId: '1:315946024042:web:c6167aba4895494b1b5e13',
    messagingSenderId: '315946024042',
    projectId: 'uncanny-woods',
    authDomain: 'uncanny-woods.firebaseapp.com',
    storageBucket: 'uncanny-woods.appspot.com',
    measurementId: 'G-EYP2L16ZB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ebjLn6pqNh-VAOI-1lGNH_E48pgS9J8',
    appId: '1:315946024042:android:9ff0c3c247323e251b5e13',
    messagingSenderId: '315946024042',
    projectId: 'uncanny-woods',
    storageBucket: 'uncanny-woods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4LuszCusyKhYtLCWj9iJlvxzxOU8rL3Y',
    appId: '1:315946024042:ios:17811995434f6a4e1b5e13',
    messagingSenderId: '315946024042',
    projectId: 'uncanny-woods',
    storageBucket: 'uncanny-woods.appspot.com',
    iosBundleId: 'com.example.uncannyWoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4LuszCusyKhYtLCWj9iJlvxzxOU8rL3Y',
    appId: '1:315946024042:ios:17811995434f6a4e1b5e13',
    messagingSenderId: '315946024042',
    projectId: 'uncanny-woods',
    storageBucket: 'uncanny-woods.appspot.com',
    iosBundleId: 'com.example.uncannyWoods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh9Y6oG9Cwvwaz4v8_uek-wS5i-0A95H0',
    appId: '1:315946024042:web:4fbf2d141986be581b5e13',
    messagingSenderId: '315946024042',
    projectId: 'uncanny-woods',
    authDomain: 'uncanny-woods.firebaseapp.com',
    storageBucket: 'uncanny-woods.appspot.com',
    measurementId: 'G-HEYG7JMGE2',
  );
}
